### PR TITLE
Merge bazel build master

### PR DESCRIPTION
**Pull request by tian000**
This just merges master from bazel build

### CODE REVIEW

**Comment by simonyun** [comment]
you sneaking in `fetch_sources=False` into the merge commit?

**Comment by tian000** [comment]
@simonyun you added fetch_sources to this method. But the methods that call this method do not pass in fetch_sources. So I am just defaulting it here so that things build. I will do a second PR, where I bubble fetch_sources up to be set at scala_repositories. 

This PR i just meant to be a merge from bazelbuild/master with as few changes as possible.

**Review by mattforbes-gr — COMMENTED** [review]
I don't know the history of why we maintain a fork, so not sure I should approve this. What's stopping us from using upstream rules_scala?

**Comment by tian000** [comment]
@mattforbes-gr we want fetch_sources for when we get jar files from maven. Which is why we maintain a fork. I have an issue (which maintainer supports) to merge our modifications upstream, but its waiting on @simonyun for legal approval.

**Comment by tian000** [comment]
@mattforbes-gr see https://github.com/ConsultingMD/rules_scala/pull/10 for changes we want to be able to get sources for the scala jars we get from maven

**Review by mattforbes-gr — APPROVED** [review]
Gotcha sgtm then

**Comment by simonyun** [comment]
rubber stamp

**Pull request merged**
